#!/usr/bin/env python2
import sys
import re
lines = sys.stdin.read().splitlines()
rege = "Date:   [A-Z][a-z]{2} [A-Z][a-z]{2} [1-9][0-9]? ([0-9]{2}:){2}[0-9]{2} [0-9]{4} "
outs = []
outspos = []
for i in range(1, 10):
    match = rege + "-0" + str(i) + "00"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outs.append("-0" + str(i) + "00" + " " + str(count))
for i in range(11,14):
    match = rege + "\+" + str(i) + "00"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outspos.append("+" + str(i) + "00" + " " + str(count)) 
for i in range(10):
    match = rege + "\+0" + str(i) + "00"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outspos.append("+0" + str(i) + "00" + " " + str(count))
for i in [3, 4, 5, 6, 9]:
    match = rege + "\+0" + str(i) + "30"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outspos.append("+0" + str(i) + "30" + " " + str(count))
for i in [3, 4]:
    match = rege + "\+0" + str(i) + "30"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outspos.append("+0" + str(i) + "30" + " " + str(count))
for i in [5]:
    match = rege + "\+0" + str(i) + "45"
    count = 0
    for j in range(len(lines)):
        if re.match(match, lines[j]):
            count = count + 1
    if count > 0:
        outspos.append("+0" + str(i) + "45" + " " + str(count))
outspos.sort()
outs.sort(reverse=True)
for i in range(len(outspos)):
    outs.append(outspos[i])
for i in range(len(outs)):
    print(outs[i])
